# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.

# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#


stages:         
  - build
  - deploy

build-job:   
  image: node:14.19.0    # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Starting NPM install..."
    - |
      cat > .npmrc << EOF
      @bwr:registry=https://bwrrepo.jfrog.io/artifactory/api/npm/default-npm-local/
      //bwrrepo.jfrog.io/artifactory/api/npm/default-npm-local/:_password=$REGISTRY_PASSWORD
      @bwr:registry=https://bwrrepo.jfrog.io/artifactory/api/npm/default-npm-local/
      //bwrrepo.jfrog.io/artifactory/api/npm/default-npm-local/:_password=$REGISTRY_PASSWORD
      //bwrrepo.jfrog.io/artifactory/api/npm/default-npm-local/:username=$REGISTRY_USERNAME
      //bwrrepo.jfrog.io/artifactory/api/npm/default-npm-local/:email=$REGISTRY_EMAIL
      //bwrrepo.jfrog.io/artifactory/api/npm/default-npm-local/:always-auth=true
      EOF

    - yarn install
    - echo "Build started..."
    - yarn build
    - echo "Deploying application..."
    #- pip install awscli
    
    - echo "S3:" $AWS_S3_BUCKET_NAME 
    - apt-get update && apt-get install -y awscli
    - aws --version
    - aws s3 sync dist s3://bwr-micro-frontend-production/admin/latest
    - echo "Application successfully deployed."
